# -*- coding: utf-8 -*-
"""NLP_HW3_NTHU_113078506.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JTu0qu7MLuamA7Vkic4xzSw3OmRj6klG
"""

!pip install evaluate

!pip install datasets==2.21.0

from transformers import BertTokenizer, BertModel
from datasets import load_dataset
from evaluate import load
import torch
from torch.utils.data import Dataset, DataLoader
from torch.optim import AdamW
from tqdm import tqdm
device = "cuda" if torch.cuda.is_available() else "cpu"
import torch.nn as nn
#  You can install and import any other libraries if needed

# Some Chinese punctuations will be tokenized as [UNK], so we replace them with English ones
token_replacement = [
    ["：" , ":"],
    ["，" , ","],
    ["“" , "\""],
    ["”" , "\""],
    ["？" , "?"],
    ["……" , "..."],
    ["！" , "!"]
]

tokenizer = BertTokenizer.from_pretrained("google-bert/bert-base-uncased", cache_dir="./cache/")

class SemevalDataset(Dataset):
    def __init__(self, split="train") -> None:
        super().__init__()
        assert split in ["train", "validation", "test"]
        self.data = load_dataset(
            "sem_eval_2014_task_1", split=split, trust_remote_code=True, cache_dir="./cache/"
        ).to_list()

    def __getitem__(self, index):
        d = self.data[index]
        # Replace Chinese punctuations with English ones
        for k in ["premise", "hypothesis"]:
            for tok in token_replacement:
                d[k] = d[k].replace(tok[0], tok[1])
        return d

    def __len__(self):
        return len(self.data)

data_sample = SemevalDataset(split="train").data[:3]
print(f"Dataset example: \n{data_sample[0]} \n{data_sample[1]} \n{data_sample[2]}")

# Define the hyperparameters
# You can modify these values if needed
lr = 3e-5
epochs = 3
train_batch_size = 8
validation_batch_size = 8

train_set.data

# TODO1: Create batched data for DataLoader
# `collate_fn` is a function that defines how the data batch should be packed.
# This function will be called in the DataLoader to pack the data batch.

def collate_fn(batch):
    # TODO1-1: Implement the collate_fn function
    # Write your code here
    # The input parameter is a data batch (tuple), and this function packs it into tensors.
    # Use tokenizer to pack tokenize and pack the data and its corresponding labels.
    # Return the data batch and labels for each sub-task.
    premises = [d["premise"] for d in batch]
    hypotheses = [d["hypothesis"] for d in batch]
    tokenized = tokenizer(
        premises,
        hypotheses,
        truncation=True,
        padding=True,
        return_tensors="pt", #turn output to PyTorch tensor
        max_length=128
    )

    relatedness_score = torch.tensor([float(d['relatedness_score']) for d in batch],
                                     dtype = torch.float)

    entailment_labels = torch.tensor(
        [int(d['entailment_judgment']) for d in batch],
                                     dtype = torch.long)
    tokenized['relatedness_score'] = relatedness_score
    tokenized['entailment_judgment'] = entailment_labels

    return tokenized

# TODO1-2: Define your DataLoader
train_set = SemevalDataset(split="train")
validation_set = SemevalDataset(split="validation")
test_set = SemevalDataset(split="test")


dl_train = DataLoader(
    train_set,
    batch_size=32,
    shuffle=True,
    collate_fn=collate_fn
)
dl_validation = DataLoader(
    validation_set,
    batch_size=32,
    shuffle=True,
    collate_fn=collate_fn
)
dl_test = DataLoader(
    test_set,
    batch_size=32,
    shuffle=True,
    collate_fn=collate_fn
)

# TODO2: Construct your model
class MultiLabelModel(torch.nn.Module):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Write your code here
        # Define what modules you will use in the model
        # Please use "google-bert/bert-base-uncased" model (https://huggingface.co/google-bert/bert-base-uncased)
        # Besides the base model, you may design additional architectures by incorporating linear layers, activation functions, or other neural components.
        # Remark: The use of any additional pretrained language models is not permitted.
        self.bert = BertModel.from_pretrained("google-bert/bert-base-uncased", cache_dir="./cache/")
        self.regressor = nn.Sequential(
            nn.Linear(768, 256),
            nn.ReLU(),
            nn.Linear(256, 1)
            )
        self.classifier = nn.Sequential(
            nn.Linear(768, 256),
            nn.ReLU(),
            nn.Linear(256, 3)
        )


    def forward(self, **kwargs):
        # Write your code here
        # Forward pass
        outputs = self.bert(**kwargs)
        pooled_output = outputs.pooler_output
        relatedness_score = self.regressor(pooled_output).squeeze(-1)
        entailment_judgement = self.classifier(pooled_output)
        return relatedness_score, entailment_judgement

# TODO3: Define your optimizer and loss function

model = MultiLabelModel().to(device)
# TODO3-1: Define your Optimizer
optimizer = torch.optim.AdamW([
    {"params": model.bert.parameters(), "lr": 2e-5},
    {"params": model.regressor.parameters(), "lr": 5e-5},
    {"params": model.classifier.parameters(), "lr": 1e-4},
])

# TODO3-2: Define your loss functions (you should have two)
# Write your code here
loss_regressor = nn.MSELoss()
loss_classifier = nn.CrossEntropyLoss()

# scoring functions
psr = load("pearsonr")
acc = load("accuracy")

best_score = 0.0
for ep in range(epochs):
    pbar = tqdm(dl_train)
    pbar.set_description(f"Training epoch [{ep+1}/{epochs}]")
    model.train()
    # TODO4: Write the training loop
    # train your model
    for batch in pbar:
      # clear gradient
      optimizer.zero_grad()

      for k in batch:
        if isinstance(batch[k], torch.Tensor):
                batch[k] = batch[k].to(device)

      # forward pass
      relatedness_pred, entailment_pred = model(
            input_ids=batch["input_ids"],
            attention_mask=batch["attention_mask"]
        )

      # compute loss
      loss_reg = loss_regressor(relatedness_pred,batch['relatedness_score'])
      loss_cls = loss_classifier(entailment_pred,batch['entailment_judgment'])


      # back-propagation
      loss_reg.backward(retain_graph=True)
      loss_cls.backward()

      # model optimization
      torch.nn.utils.clip_grad_norm_(model.parameters(), max_norm=1.0)

      optimizer.step()

    pbar = tqdm(dl_validation)
    pbar.set_description(f"Validation epoch [{ep+1}/{epochs}]")
    model.eval()

    all_related_preds = []
    all_related_truth = []
    all_entail_preds = []
    all_entail_truth = []
    # TODO5: Write the evaluation loop
    # Evaluate your model
    with torch.no_grad():
      for batch in pbar:
        for k in batch:
          if isinstance(batch[k], torch.Tensor):
                batch[k] = batch[k].to(device)
        relatedness_pred, entailment_pred = model(
            input_ids=batch["input_ids"],
            attention_mask=batch["attention_mask"]
        )

        all_related_preds.extend(relatedness_pred.cpu().tolist())
        all_related_truth.extend(batch['relatedness_score'].cpu().tolist())

        entailment_pred = entailment_pred.argmax(dim=1)
        all_entail_preds.extend(entailment_pred.cpu().tolist())
        all_entail_truth.extend(batch['entailment_judgment'].cpu().tolist())

    # Compute the evaluation scores (PearsonCorr, Accuracy)
    # Output all the evaluation scores (PearsonCorr, Accuracy)
    pearson_corr = psr.compute(predictions=all_related_preds, references=all_related_truth)["pearsonr"]
    accuracy = acc.compute(predictions=all_entail_preds, references=all_entail_truth)["accuracy"]
    print(f"Epoch {ep+1}: PearsonCorr: {pearson_corr}, Accuracy: {accuracy}")
    # print(f"F1 Score: {f1.compute()}")

    if pearson_corr + accuracy > best_score:
        best_score = pearson_corr + accuracy
        torch.save(model.state_dict(), f'./best_model.ckpt')

with torch.no_grad():
  for batch in pbar:
    inputs = {k: v.to(device) for k, v in batch.items() if isinstance(v, torch.Tensor)}

    # 檢查輸入的 batch size
    print(f"Input batch size: {inputs['input_ids'].shape[0]}")
    print(f"Label batch size: {batch['entailment_judgment'].shape[0]}")

    # Forward pass
    relatedness_score, entail_logits = model(
            input_ids=inputs["input_ids"],
            attention_mask=inputs["attention_mask"],
            token_type_ids=inputs["token_type_ids"]
        )

    # 檢查輸出的 batch size
    print(f"Output batch size: {entail_logits.shape[0]}")

    entailment_pred = entail_logits.argmax(dim=1)
    print(f"Pred size: {len(entailment_pred)}")

    break  # 只跑第一個 batch 來 debug

# Load the model
model = MultiLabelModel().to(device)
model.load_state_dict(torch.load(f"./best_model.ckpt", weights_only=True))

# Test Loop
pbar = tqdm(dl_test, desc="Test")
model.eval()
all_entail_preds = []
all_entail_truth = []
all_related_preds = []
all_related_truth = []

# TODO6: Write the test loop
# We have loaded the best model with the highest evaluation score for you
# Please implement the test loop to evaluate the model on the test dataset
# We will have 10% of the total score for the test accuracy and pearson correlation
with torch.no_grad():
  for batch in pbar:
    inputs = {k: v.to(device) for k, v in batch.items() if isinstance(v, torch.Tensor)}

    # Forward pass
    relatedness_pred, entailment_pred = model(
            input_ids=inputs["input_ids"],
            attention_mask=inputs["attention_mask"],
            token_type_ids=inputs["token_type_ids"]
        )

    entailment_pred = entailment_pred.argmax(dim=1)

    # Collect predictions
    all_related_preds.extend(relatedness_pred.squeeze().cpu().tolist())
    all_related_truth.extend(batch["relatedness_score"].cpu().tolist())

    all_entail_preds.extend(entailment_pred.cpu().tolist())
    all_entail_truth.extend(batch["entailment_judgment"].cpu().tolist())

# Compute scores
pearson_corr = psr.compute(predictions=all_related_preds, references=all_related_truth)["pearsonr"]
accuracy = acc.compute(predictions=all_entail_preds, references=all_entail_truth)["accuracy"]

print(f"\n Final Test Results:")
print(f"Pearson Correlation (relatedness): {pearson_corr:.4f}")
print(f"Accuracy (entailment): {accuracy:.4f}")